name: CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dagger/dagger-for-github@v7
        with:
          verb: call
          module: ./dagger
          args: ci --source=.
